current_version: "3.5.0"
strategy:
  name: "semver"
  part: "minor"
commit:
  author: "Jill San Luis <jill.devs@gmail.com>"
tag:
  apply: True
  format: "v{version}"
auto_remote_push: True
tracked_files:
  - README.md
  - sample/VERSION
